### ISSUE TITLE
Introduce Grunt

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-portfolio-pro#22]
As in https://github.com/copyblogger/genesis-connect-woocommerce, introduce Grunt tasks.

**Comment by marksabbath** [comment]
Oh that's true! Thanks for the tip @nathanrice Do you have any experience on how to solve this kind of issue? Should we create a symlink, perhaps?

**Comment by nathanrice** [comment]
This is what I did in SEO Data Transporter:
https://github.com/copyblogger/seo-data-transporter/blob/develop/plugin.php

**Comment by marksabbath** [comment]
That would be way safer than creating a symlink. IMHO we would need to use your approach and in the future, think on a way to completely move from `plugin.php` to `<plugin-name>.php`. That, of course, doesn't have any rush, it's just a matter of standardization. Thanks for all your help @nathanrice! I'll add the `plugin.php` including the `require_once`.

**Comment by nathanrice** [comment]
All new plugins should use `plugin-slug.php`, but I'm not sure how we could retroactively switch existing plugins. All ideas welcome.

**Comment by marksabbath** [comment]
Totally agree with you @nathanrice I'll perform some research on how we could make this happen when updating plugins. For now, I think we can keep using your solution just to keep it rolling.

I'll add a new issue so we can track the research.

Thanks again for all your help!

**Comment by nickcernis** [comment]
Hey, @marksabbath. Is `feature/introduce-grunt` now ready for review? I wasn't sure if any more input's needed here. If I can help, let me know!

**Comment by marksabbath** [comment]
Sorry, I think it's all resolved @nickcernis Gonna create a Pull request right now.
