### ISSUE TITLE
Review srcset and itemprop tag attributes on portfolio archive images

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-portfolio-pro#25]
As titled.

**Comment by dreamwhisper** [comment]
From https://github.com/studiopress/genesis-portfolio-pro/blob/develop/lib/functions.php#L89-L112

At some point, I was working on testing changes to this. This is the last bit of code I was testing to replace the above.

```php
function genesis_portfolio_grid() {

	$image = genesis_get_image( array(
			'format'  => 'html',
			'size'    => 'portfolio',
			'context' => 'archive',
			'attr'    => array ( 'alt' => the_title_attribute( 'echo=0' ), 'class' => 'portfolio-image', 'itemprop' => 'image' ),
		) );

	if ( ! empty( $image ) ) {
			genesis_markup( array(
				'open'    => '<div class="portfolio-featured-image"><a href="' . get_permalink() . '" aria-hidden="true">',
				'close'   => '</a></div>',
				'content' => $image,
				'context' => 'portfolio-pro',
			) );
		}

}
```

**Comment by nickcernis** [comment]
Thanks, @dreamwhisper.

Noting `'itemprop' => 'image'` and use of `genesis_markup` as the additions above. Will review for 1.2.

**Comment by nickcernis** [comment]
Ready for testing. I added the itemprop and switched to genesis_markup as suggested.

No further changes were needed to output srcset for responsive images — WP adds them if image thumbnails with the same ratio as the original thumbnail are available.

### To test
Branch: fix/archive-img-attributes

- Confirm that `itemprop="image"` appears on images in the portfolio archive.
- Confirm that the portfolio archive layout is unchanged.
