### ISSUE TITLE
Widget: Undefined index

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-portfolio-pro#27]
When using the widget, if I choose not to show the title, I get an undefined index.

`Notice: Undefined index: show_byline in /home/dreamwhi/public_html/dev8/wp-content/plugins/genesis-portfolio-pro/lib/views/widget/portfolio.php on line 82`

I think just remove `|| $instance['show_byline']` there.

**Comment by nickcernis** [comment]
Thank you! Fixed in b5c8373.
