### ISSUE TITLE
Order of Portfolio Items

### ISSUE THREAD

**Issue by susannelson** [studiopress/genesis-portfolio-pro#9]
When using the Order field in the Attributes box, the portfolio items do not get reordered.

![image](https://cloud.githubusercontent.com/assets/3220438/14209473/4058db6e-f7f2-11e5-89b8-7a376d0f9744.png)

No matter what setting is used, the items are always displayed in reverse chronological order.

**Comment by carasmo** [comment]
Amazed this has not been addressed. 

This plugin uses the same default query as blog posts. You need to modify the query.

Anyone wanting to order by ASC and the Menu Order (which is the order you input in the Order field) add the following:
```

function yourprefix_order_by_menu_order_asc_genesis_portfolio_pro( $query ) {
    
    if ( $query->is_post_type_archive('portfolio') && $query->is_main_query() ) {
        
        $query->set( 'orderby', 'menu_order' );
        
        $query->set( 'order', 'ASC' );
    }
    
}
add_action( 'pre_get_posts', 'yourprefix_order_by_menu_order_asc_genesis_portfolio_pro' );
```

**Comment by cre8tivediva** [comment]
This is exactly what I've been looking for! Thank you for sharing this. I think it's odd that it's not in there too. I get this question a lot on support but also for my own clients.

**Comment by nickcernis** [comment]
Genesis Portfolio Pro 1.2 will sort portfolio archives by menu order first (ASC), then date (DESC).

Test in `feature/archive-page-order` branch.

### Setup
1. Add two portfolio items.
2. Set their 'order' values in the Attributes meta box.

### Confirm:
- [ ] With orders set, the lowest order item appears first.
- [ ] With orders set to 0, the newest item appears first.

**Comment by Ali-RMD** [comment]
@nickcernis Confirmed +1

**Environment:**

WordPress:
Version: 4.9.8

PHP:
Versions: 5.6.24 & 7.1.14

Genesis Framework:
Version: 2.6.1

Active Themes:
Genesis Sample - Version: 2.6.0
Essence Pro - Version: 1.0.2

Branch:
https://github.com/studiopress/genesis-portfolio-pro/tree/feature/archive-page-order

**Results:**

- [x] With orders set to non-zero values, the lowest order item appears first.
- [x] With orders set to zero, the newest item appears first.
